uint32 schema_version
DispatchBinding dispatch_binding
string primitive_name
uint8 navigation_command_type
geometry_msgs/PoseStamped navigation_target_pose
float64 navigation_value
string pose_name
float32 relative_dx
float32 relative_dy
float32 relative_dz
float32 target_x
float32 target_y
float32 target_z
float32 target_qx
float32 target_qy
float32 target_qz
float32 target_qw
float32 velocity_scaling
float32 gripper_position
string[] joint_names
float32[] joint_positions
float32 primitive_duration_sec
float32[] joint_waypoints
uint32 joint_waypoint_count
float32 waypoint_duration_sec
---
bool allowed
string reason
string error_code
string actual_registry_epoch
uint64 actual_registry_generation
string actual_registry_digest
SkillDiagnostic[] diagnostics
