schema_version: 1
kind: primitive_sequence
robot: lekiwi_handeye_realsense_grasp_pc
initial_gripper_state: none
timeout_sec: 120.0
primitive_sequence:
- primitive_name: move_to_named_pose
  pose_name: home
