"""Dependency-neutral inference manifest models and validation helpers."""

from inference_manifest.errors import (
    ManifestError,
    ManifestIntegrityError,
    ManifestPathError,
    ManifestValidationError,
)
from inference_manifest.integrity import (
    canonical_bundle_digest,
    canonical_semantic_identity_json,
    deployment_fingerprint,
    semantic_identity_fingerprint,
    verify_bundle_digest,
)
from inference_manifest.loader import (
    MANIFEST_FILENAME,
    ValidatedManifest,
    load_inference_manifest,
    load_inference_manifest_metadata,
)
from inference_manifest.metadata import ExternalDependency, PolicyFeature, PolicyMetadata, load_policy_metadata
from inference_manifest.models import (
    ArtifactBindings,
    BundleFile,
    CompiledDeployment,
    Deployment,
    DeploymentArtifact,
    DeploymentTarget,
    DeviceLink,
    Digest,
    EmbeddingMetadata,
    ExecutionRole,
    InferenceManifest,
    ManifestBundle,
    ManifestUUID,
    ModelDescriptor,
    Revision,
    SemanticIdentity,
    SemanticTensor,
    TensorBinding,
    TorchDeployment,
)
from inference_manifest.paths import (
    normalize_bundle_path,
    normalize_unique_paths,
    resolve_bundle_file,
    resolve_bundle_path,
)
from inference_manifest.schema import manifest_schema, validate_manifest_schema
from inference_manifest.writer import canonical_manifest_bytes, write_inference_manifest

__all__ = [
    "ArtifactBindings",
    "BundleFile",
    "CompiledDeployment",
    "Deployment",
    "DeploymentArtifact",
    "DeploymentTarget",
    "DeviceLink",
    "Digest",
    "EmbeddingMetadata",
    "ExecutionRole",
    "ExternalDependency",
    "InferenceManifest",
    "MANIFEST_FILENAME",
    "ManifestError",
    "ManifestBundle",
    "ManifestUUID",
    "ManifestIntegrityError",
    "ManifestPathError",
    "ManifestValidationError",
    "ModelDescriptor",
    "PolicyFeature",
    "PolicyMetadata",
    "Revision",
    "SemanticIdentity",
    "SemanticTensor",
    "TensorBinding",
    "TorchDeployment",
    "ValidatedManifest",
    "canonical_bundle_digest",
    "canonical_manifest_bytes",
    "canonical_semantic_identity_json",
    "deployment_fingerprint",
    "load_inference_manifest",
    "load_inference_manifest_metadata",
    "load_policy_metadata",
    "manifest_schema",
    "normalize_bundle_path",
    "normalize_unique_paths",
    "resolve_bundle_file",
    "resolve_bundle_path",
    "semantic_identity_fingerprint",
    "verify_bundle_digest",
    "validate_manifest_schema",
    "write_inference_manifest",
]
